FORMAT: 1A
HOST: http://staging.api.mtfan.mediotiempo.com

# MTSocial API testing
API de MT Fan test (hello dudes)

# Group Login
<a id="login" ></a>

To login into the MTSocial API API, use following calls:

- 1. `POST` your credentials in JSON body to the *login* resource. An **token** is returned back.
- 2. Use the **token** in your API calls header **X-Auth-Token**.

Remember that TT Token has **limited validity**. Once you received 401 Unauthorized Response, you need to GET new TT Token.

###Login Properties
- username (string) : User's email
- password (string) : User's password


## /login
### POST
This resource is the first. Use it to log into the API.

`Please use your MTSocial API account credentials for API calls.`

+ Request (application/json)
    + Headers

            Accept: application/json

    + Body

            {"username":"user@company.com","password":"YourPassword"}

+ Response 200 (application/json)
 
    + Body

            {"username":"tsalazar@expansion.com.mx","token":"o5245j7tn44hf1gvalbvkvgjk5t9s9cv","roles":["ROLE_ADMIN","ROLE_ROOT”]}


## /loginfb
### POST
This resource is the first. Use it to log into the API.

`Please use your MTSocial API account credentials for API calls.`

+ Request (application/json)
    + Headers

            Accept: application/json

    + Body

            {"facebookId":"692189333" }

+ Response 200 (application/json)
 
    + Body

            {"username":"tsalazar@expansion.com.mx" , "token":"o5245j7tn44hf1gvalbvkvgjk5t9s9cv","roles":["ROLE_ADMIN","ROLE_ROOT”]}



## /api/validate
Basic service to validate token, this is for testing.

Use the token retrive from login call as header X-Auth-Token.
### GET
+ Headers

            X-Auth-Token: {token}


+ Response 200 (application/json)
 
    + Body

            {"token":"o5245j7tn44hf1gvalbvkvgjk5t9s9cv","roles":["ROLE_ADMIN","ROLE_ROOT”]}

             
## /v1/person/{idUser}

Info person 
+ Parameters
    + idUser (required, number, `666`) ... Numeric `idUser` to perform action with. Has example value.
 
### Person details [GET]
+ Response 200 (application/json)

            {"id":1,"name":"Domingo Suarez Torres","email":"dsuarez@expansion.com.mx"}

# Group Sprint 2

## List of tournaments or leagues [/v1/tournaments]

   

### List of tournaments or leagues [GET]
+ Headers

            X-Auth-Token: {token}

+ Response 200 (application/json)

        [
            {
                "idLeague":23434,
                "name":"Primera Division"
            },
            {
                "idLeague":234542,
                "name": "Liga Española"
            }
        ]

## List of teams of tournaments or league [/v1/tournaments/${idLeague}/teams/]
### Lsit of teams  [GET]
+ Headers

            X-Auth-Token: {token}

+ Response 201 (application/json)

        {
            "idLeague":23434,
            "name":"Primera Division",
            "teams":
                [
                    {
                        "idTeam": 56456, 
                        "name": "América", 
                        "shortName":"CA",
                        "following":1,
                        "urlImagen":"http://gex.mediotiempo.media/23123.jpg"
                    }, 
                    {
                        "idTeam": 2234234,
                        "name": "Cruz Azul", 
                        "shortName": "CAz"
                        "following":0,
                        "urlImage":"http://gex.mediotiempo.media/23123.jpg"
                    }
                ]
         }

## follow a team [/v1/teams/follow{idUser,idTeam, idLeague}]
Request Team Follow 

+ Parameters
    + idUser (required, number, `666`) ... Numeric `idUser` to perform action with. Has example value.
    + idTeam (required, number, `56456`) ... Numeric `idTeam`  of the team that we want to follow
    + idLeague (required, number, `23434`) ... Numeric `idLeague` of league or tournament to which the football team belongs 

### Seguir un equipo [POST]
+ Response 200 (application/json)
 + Header

            X-My-Header: The Value

    + Body

            { "code": 0, "message": "Successful" }
            

## List of followings [/v1/followings{idUser}]

List of followings
+ Parameters
    + idUser (required, number, `666`) ... Numeric `idUser` to perform action with. Has example value.
    
### Listado de amigos a los que sigo  [GET]
+ Response 201 (application/json)

         [
            {
                "idUser":43234,
                "name":"Pedro Perez",
                "urlImagen":"http://gex.mediotiempo.media/32323.jpg"
            },
            {
                "idUser":32234,
                "name":"Daniel Ramos",
                "urlImagen":"http://gex.mediotiempo.media/32323.jpg"
            },
            {
                "idUser":43234,
                "name":"Moises Vélez",
                "urlImagen":"http://gex.mediotiempo.media/32323.jpg"
            },
            {
                "idUser":43234,
                "name":"Bernardino Guerrero",
                "urlImagen":"http://gex.mediotiempo.media/32323.jpg"
             }
        ]


## Request user following [/v1/user/follow{idUser,idUserFollow}]
Following a user 

+ Parameters
    + idUser (required, number, `666`) ... Numeric `idUser` to perform action with. Has example value.
    + idUserFollow (required, number, `2234234`) ... Numeric `idUserFollow`  of the user that we want to follow. Has example value.

### Request a team follow [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "code": 0, "message": "Successful" }



## User's profile [/v1/user/profile{idUser}]

Get user's profile with three last activities  

Meaning of the values for the tag <b>type</b> in the response:

<ol type="1" start="1">
<li> Like a post </li>
<li> Share a post </li>
<li> Comment a post with or without picture </li>
<li> Checkin </li>
<li> Following a user</li> 
<li> Following a match </li>
<li> Following a team </li>
<li> Comment about match </li>
<li> Photos about event</li>
<li> Post a comment with or without picture </li>
</ol>

+ Parameters
    + idUser (required, number, `666`) ... Numeric `idUser` to perform action with. Has example value.

### GET
+ Headers

            X-Auth-Token: {token}


+ Response 200 (application/json)
 
    + Body

            {
            "name":"Cristiano Ronaldo",
            "followings":9
            "followers":23248,
            "badges": 30,
            "snapShot":[
                {
                    "urlThumb":"http://mt.scoial.media.thumb/3434.jpg", 
                    "url":"http://mt.scoial.media.picture/3434.jpg", 
                    "text":nil
                },
                {
                    "urlThumb":"http://mt.scoial.media.thumb/343.jpg", 
                    "url":"http://mt.scoial.media.picture/343.jpg", 
                    text:nil
                }, 
                {
                    "urlThumb":"http://mt.scoial.media.thumb/7434.jpg", 
                    "url":"http://mt.scoial.media.picture/7434.jpg",
                    "text":nil
                }
                ]
            "activity":[
                {
                    "idActivity":23423,
                    "type":4, 
                    "urlImg":{
                        "urlThumb":"http://mt.scoial.media.picture.user.thumb/666.png", 
                        "url":"http://mt.scoial.media.picture.user/666.png", 
                        "text":nil
                    }, 
                    "text":"Hoy vamos a golear a los merengues"
                },
                {
                    "idActivity":53453,
                    "type":10,  
                    "urlImg":nil, 
                    text:"Hoy si gana mi equipo"
                }, 
                {
                    "idActivity":666,  
                    "type":5, 
                    "urlImg":{
                        "urlThumb":"http://mt.scoial.media.picture.user.thumb/666.png", 
                        "url":"http://mt.scoial.media.picture.user/666.png", 
                        "text":nil
                    }, 
                    "text":nil
                }
                ]
            }

## Get user's pictures [/v1/user/pictures{idUser}]
Get a list of user's pictures

+ Parameters
    + idUser (required, number, `666`) ... Numeric `idUser` to perform action with. Has example value.

### GET
+ Headers

            X-Auth-Token: {token}
            
+ Response 200 (application/json)
    + Body
    
            [
                {
                    "idPicture":23423,
                    "urlThumb":"http://mt.scoial.media.thumb/3434.jpg", 
                    "url":"http://mt.scoial.media.picture/3434.jpg", 
                    "text":nil,
                    "comments":100
                },
                {
                    "idPicture":23424,
                    "urlThumb":"http://mt.scoial.media.thumb/343.jpg", 
                    "url":"http://mt.scoial.media.picture/343.jpg", 
                    "text":nil,
                    "comments":0
                }, 
                {   
                    "idPicture":23425,
                    "urlThumb":"http://mt.scoial.media.thumb/7434.jpg", 
                    "url":"http://mt.scoial.media.picture/7434.jpg",
                    "text":"Yo en la bombonera",
                    "comments":3432
                }
            ]

## Followers [/v1/user/followers{idUser}]
Get user's followers list
### GET
+ Parameters
   + idUser (required, number, `666`) ... Numeric `idUser` to perform action with. Has example value.
  
+ Response 200 (application/json) 

            [{
                "name":"Pedro Perez",
                "idUser":23434, 
                "status":"follow", 
                "avatar":{
                    "urlThumb":"http://mt.scoial.media.thumb/3434.jpg", 
                    "url":"http://mt.scoial.media.picture/3434.jpg", 
                    "text":nil
                    }
                },
                {
                    "name":"Luis Orosco",
                    "idUser":44234,
                    "status":"follow",
                    "avatar":{
                        "urlThumb":"http://mt.scoial.media.thumb/3434.jpg", 
                        "url":"http://mt.scoial.media.picture/3434.jpg", 
                        "text":nil
                        }
                },
                {
                "name":"Guillermo García",
                "idUser":9434, 
                "status":"follow", 
                "avatar":{
                    "urlThumb":"http://mt.scoial.media.thumb/3434.jpg", 
                    "url":"http://mt.scoial.media.picture/3434.jpg", 
                    "text":nil
                    }
                }
            ]

## Block a user [/v1/user/blockUser{idUser, idUserBlocked}]
Block a user 

+ Parameters
    + idUser (required, number, `666`) ... Numérico `idUser` user logged
    + idUserBlocked (required, number, `966`) ... Numérico `idUserBlocked` user to block.

### POST
+ Request (application/json)

        { "idUser": 666,"token":"ADASqwe21312323ADFf" }

+ Response 201 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "code": 0, "message": "Successful" }
            
            
## Unblock a user [/v1/user/unblockUser{idUser, idUserUnblock}]
Block a user 

+ Parameters
    + idUser (required, number, `666`) ... Numérico `idUser` user logged
    + idUserUnblock (required, number, `966`) ... Numérico `idUserUnblock` user to unblock.

### POST
+ Request (application/json)

        { "idUser": 666,"token":"ADASqwe21312323ADFf" }

+ Response 201 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "code": 0, "message": "Successful" }            
            
## User's activity [/v1/user/timeline{idUser, idUserTimeLine}]

Meaning of the values for the tag <b>type</b> in the response:

<ol type="1" start="1">
<li> Like a post </li>
<li> Share a post </li>
<li> Comment a post with or without picture </li>
<li> Checkin </li>
<li> Following a user</li> 
<li> Following a match </li>
<li> Following a team </li>
<li> Comment about match </li>
<li> Photos about event</li>
<li> Post a comment with or without picture </li>
</ol>

+ Parameters
    + idUser (required, number, `666`) ... Numeric `idUser` User logged in the app
    + idUserTimeLine (required, number, `966`) ... Numeric `idUserTimeLine` of what we want to see the activity on the App.
    

    
### POST
+ Request (application/json)

            { "idUser": 666,"token":"ADASqwe21312323ADFf" }


+ Response 201 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            [{"idActivity":23453, 
                "type":1,  
                "urlImg":null, 
                "text":"Hoy si gana mi equipo", 
                "userRelated":{
                        "idUser":34433, 
                        "name":"Cristiano Ronaldo", 
                        "urlImagen":"http://gex.mediotiempo.media/32323.jpg"
                }, 
                "comments":0
            },
            {
                "idActivity":23454, 
                "type":2,  
                "urlImg":null, 
                "text":"Hoy si gana mi equipo", 
                "userRelated":{
                    "idUser":34433,
                    "name":"Cristiano Ronaldo",
                    "urlImagen":"http://gex.mediotiempo.media/32323.jpg"
                    }, 
                    "comments":0
            },
            {
                "idActivity":23455,
                "type":3,
                "urlImg":null,
                "text":"Hoy si gana mi equipo",
                "userRelated":{
                    "idUser":34433, 
                    "name":"Cristiano Ronaldo", 
                    "urlImagen":"http://gex.mediotiempo.media/32323.jpg"}, 
                    "comments":1
            },
            {
                "idActivity":23456, 
                "type":4,  
                "urlImg":{
                    "urlThumb":"http://mt.scoial.media.picture.user.thumb/666.png", 
                    "url":"http://mt.scoial.media.picture.user/666.png", "text":nil
                }, 
                "text":"En el estadio Azteca", 
                "comments":3450, 
                "checkinInfo":{
                    "idChekin":908, 
                    "name":"Estadio Azteca"
                }
            },
            {
                "idActivity":23457, 
                "type":5,
                "urlImg":null, 
                "text":null, 
                "comments":0, 
                "userRelated":{
                    "idUser":34433, 
                    "name":"Cristiano Ronaldo", 
                    "urlImagen":"http://gex.mediotiempo.media/32323.jpg"}
                },
            {
                "idActivity":23957, 
                "type":6,
                "urlImg":null,
                "text":null,
                "comments":0,
                "match":{
                    "idMatch":9097
                    local:{
                        "idTeam":1230,
                        "name":"Real Madrid", 
                        "shortName":"RealM"
                        "urlImagen":"http://gex.mediotiempo.media/realM.jpg"
                    },
                    visiting:{
                        "idTeam":1237,
                        "name":"Everton", 
                        "shortName":"EVE"
                        "urlImagen":"http://gex.mediotiempo.media/Everton.jpg"
                    }
                }
            },
            {
                "idActivity":23458, 
                "type":7,
                "urlImg":null,
                "text":null,
                "comments":0,
                "team":{
                    "idTeam":13344,
                    "name":"Pumas de la UNAM",
                    "shortName":"Pumas",
                    "urlImagen":"http://gex.mediotiempo.media/32323.jpg"
                }
            },
            {
                "idActivity":23458, 
                "type":8,
                "text":"Este partido deja mucho que desear",
                "comments":10,
                "idUser":666
                "userName":"Bernardino Guerrero"
               "match":{
                    "idMatch":9097
                    local:{
                        "idTeam":1230,
                        "name":"Real Madrid", 
                        "shortName":"RealM"
                        "urlImagen":"http://gex.mediotiempo.media/realM.jpg"
                    },
                    visiting:{
                        "idTeam":1237,
                        "name":"Everton", 
                        "shortName":"EVE"
                        "urlImagen":"http://gex.mediotiempo.media/Everton.jpg"
                    }
                },
            {
                "idActivity":21479, 
                "type":9,
                "idUser":666
                "userName":"Bernardino Guerrero"
               "match":{
                    "idMatch":9097
                    local:{
                        "idTeam":1230,
                        "name":"Real Madrid", 
                        "shortName":"RealM"
                        "urlImagen":"http://gex.mediotiempo.media/realM.jpg"
                    },
                    visiting:{
                        "idTeam":1237,
                        "name":"Everton", 
                        "shortName":"EVE"
                        "urlImagen":"http://gex.mediotiempo.media/Everton.jpg"
                    }
                },
                "photosMatch":{
                    "idAlbum":43123,
                    photos:[
                        {
                            "urlImg":"http://mtsocial.partidos/234234.png",
                            "text":null
                        },
                        {
                            "urlImg":"http://mtsocial.partidos/234235.png",
                            "text":"Que golazoooo...!"
                        }
                    ]
                },
            {
                "idActivity":23458,
                "type":10,
                "urlImg":"http://mtsocial.partidos/93234.png",
                "text":"Hoy si gana mi equipo"
            }]

         

## Get a comment's list of activity  [/v1/user/timeline{idUser, idEvent}]
+ Parameters
    + idUser (required, number, `666`) ... Numeric `idUser` user logged. 
    + idEvent (required, number, `23458`) ... Numeric  `idEvent` of what we want get comments

### GET
+ Headers

            X-Auth-Token: {token}
            
+ Response 200 (application/json)
    + Body
    
            [{
                "idComment":1231, 
                "text":"Este partido deja muho que desear", 
                "timeStamp":2342340999,
                "user":{
                    "name":"Bernardino Guerrero",
                    "idUser":9434, 
                    "status":"follow", 
                    "avatar":{
                        "urlThumb":"http://mt.scoial.media.thumb/3434.jpg", 
                        "url":"http://mt.scoial.media.picture/3434.jpg", 
                    }
                }
            },
            {
                "idComment":1231, 
                "text":"Tú no sabes de futbol", 
                "timeStamp":2342340909,
                "usuario":{
                    "name":"Tony Vielmas",
                    "idUser":1334, 
                    "status":"follow", 
                    "avatar":{
                        "urlThumb":"http://mt.scoial.media.thumb/1334.jpg", 
                        "url":"http://mt.scoial.media.picture/1334.jpg", 
                    }
                }
            }
            ]

# Group Sprint 3
Partidos (en vivo, anteriores, proximos) , Torneos y Mis Partidos

## Partidos [/matches]
### Listado de partidos [GET]
Este servicio trae como respuesta los partidos de las diferentes ligas. Se pide un criterio de tiempo (pasado, presente, futuro) para listarlos. Valor esperado:  `option` ( `past` <b>partidos anteriores</b> , `next` <b>partidos proximos</b>  y`today`  <b>partidos en vivo</b> ).


+ Request (application/json)

    + Headers
    
            X-Auth-Token: {token}

    + Body
    
            
            {"option": "optionMatch"}


+ Response 200 (application/json)


        {
        timestamp: "2014-03-12T15:43:59Z",
        torneos: {
            429: {
                nombre: "English Barclays Premier League 2013",
                fases: {
                    1: {
                        nombre: "Regular",
                        jornadas: {
                            29: {
                            nombre: "Jornada 29",
                            nombreCorto: "J29",
                            partidos: {
                                50143: {
                                    linkPrevio: null,
                                    linkCronica: null,
                                    linkGaleria: null,
                                    linkFicha: null,
                                    local: "Newcastle",
                                    localCorto: "NEW",
                                    localCss: "Newcastle",
                                    federacionLocal: "FA",
                                    visitante: "Everton",
                                    visitanteCorto: "EVE",
                                    visitanteCss: "Everton",
                                    federacionVisitante: "FA",
                                    goles_local: null,
                                    goles_visitante: null,
                                    penales_local: null,
                                    penales_visitante: null,
                                    startTime: "2014-03-09T16:00:00Z",
                                    startTimeT1: null,
                                    endTimeT1: null,
                                    startTimeT2: null,
                                    endTimeT2: null,
                                    startTimeTE1: null,
                                    endTimeTE1: null,
                                    startTimeTE2: null,
                                    endTimeTE2: null,
                                    endTimeGame: null,
                                    compTimeT1: 0,
                                    compTimeT2: 0,
                                    compTimeTE1: 0,
                                    compTimeTE2: 0,
                                    hasExtraTime: false,
                                    hasPenalties: false,
                                    esFavorito: true,
                                    comentariosCantidad: 45
                                }
                            }
                        }
                    }
                }
            }
        },
        432: {},
        447: {}
        }


+ Response 404 (application/json)
 
        {
            timestamp: "2014-03-12T16:03:40Z",
            portada: "noticias",
            torneos: {
                info: "no se encontraron partidos"
            }
        }


## Ficha de partido [/reviews]
Fuente: http://euro.mediotiempo.com/html/feeds/sindicacion/partidos/ficha/5/513/51343.xml

### Ficha de partido [GET]
Servicio que debe traer la info del partido, goles, anotadores, si ah sido seguido, encuesta y si ah votado en la encuesta. Traerá datos siempre y cuando el partido haya finalizado. Valor a enviar: `idMatch`

+ Request (application/json)

    + Headers
    
            X-Auth-Token: {token}

    + Body

            {"idMatch":"50143"}
            

+ Response 200 (application/json)


        {
            torneo: {
                id: 447,
                name: Clausura 2014,
                start: "2014-01-03"
            },
            partido:{
                id: 51343,
                jornada: 7,
                fase: 1,
                bitacora: true,
                galeria: true
            },
            fecha: "2010-08-28 18:00:00",
            estadio: Morelos,
            estadioLat: 19.696961,
            estadioLon: -101.202165,
            localId: 31,
            localNombre: Morelos,
            visitanteId: 20,
            visitanteNombre: América,
            totalGolesLocal : 2,
            totalGolesVisitante : 3,
            fotos: {
                [
                    "http://gex.mediotiempo.media/23128.jpg",
                    "http://gex.mediotiempo.media/23126.jpg",
                    "http://gex.mediotiempo.media/23125.jpg",
                ]
            },
            haVotado: false,
            votacion: {
                local: 63,
                empate: 17,
                visitante: 20
            },
            goles: {
                [
                    gol: { 
                        id: 1,
                        idequipoanotado: 31,
                        idequiporecibido: 20,
                        min: 61
                        tipo: 1,
                        forma: 1,
                        marcador: “1-0”,
                        jugadorId: 9910,
                        jugador: “Christian Valdez”
                    },
                    gol: {
                        id: 1,
                        idequipoanotado: 31,
                        idequiporecibido: 20,
                        min: 86
                        tipo: 1,
                        forma: 1,
                        marcador: “1-0”,
                        jugadorId: 9910,
                        jugador: “Christian Valdez”
                    }
                ]
            }
        }


+ Response 404 (application/json)


        error: {
            timestamp: "2014-03-12T16:03:40Z",
            info: "no se encontro ficha"
        }


## Votaciones de partido [/polls]
Las votaciones son pequeñas encuestas realizadas por partido. Los elementos (`opcionEncuesta`) por votar son `local`, `empate` y `visitante`.

### Listado de Votaciones[GET]
Este servicio trae para un partido dado, las votaciones realizadas por los usuarios. Valor a enviar: `idMatch`.

+ Request (application/json)

    + Headers
    
            X-Auth-Token: {token}
    + Body

            {"idMatch":"50143" }
            

+ Response 200 (application/json)


        votacion: {
            total: 100 ,
            local: 60 ,
            empate: 17 ,
            visitante: 23
        }

+ Response 404 (application/json)


        {
            code : 404 ,
            message: "no se encontro encuesta"
        }


### Agregar votacion de partido [PUT]
Este servicio agrega un voto a la encuesta. Admite uno de tres valores para realizar la votacion: `local`, `empate` o `visitante`.


+ Request (application/json)

    + Headers
    
            X-Auth-Token: {token}

    + Body

            {"idMatch":"50143" , "option": "opcionEncuesta" }
            

+ Response 200 (application/json)


        {
            total: 104 ,
            local: 64 ,
            empate: 17 ,
            visitante: 23
        }

## Comentarios de Partido [/match_comments]


### Listado de comentarios de partido [GET]
El servicio regresa los comentarios asociados con un partido. Valores esperado: `idMatch` , `start` (id del ultimo comentario) , `count` (cantidad de cometarios a traer). En caso de no venir `start` o `count` se asume el default: `start` = ultimo comentario de partido en BD y `count` = 20.

+ Request (application/json)

    + Headers
    
            X-Auth-Token: {token}

    + Body

            {"idMatch":"50143" , "start":"678" , "count":"20" }
            


+ Response 200 (application/json)


        [
            {
                idComentario: 678 ,
                idUser: 7895
                nombreUser: "Luis Ramirez",
                urlImagenUser: "http://gex.mediotiempo.media/32323.jpg" , 
                timestamp: "2014-03-12T15:43:59Z",
                titulo: "Vamos a ganar"
                comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non nunc gravida, porta urna nec, volutpat quam. Nullam consequat lacus ante, et auctor justo congue ut. Integer viverra viverra massa id malesuada"
            },
            {
                idComentario: 679 ,
                idUser: 6544
                nombreUser: "Alberto Castro",
                urlImagenUser: "http://gex.mediotiempo.media/32323.jpg" , 
                timestamp: "2014-03-12T15:43:59Z",
                titulo: "Vamos a ganar"
                comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non nunc gravida, porta urna nec, volutpat quam. Nullam consequat lacus ante, et auctor justo congue ut. Integer viverra viverra massa id malesuada"
            },
            {
                idComentario: 680 ,
                idUser: 1258
                nombreUser: "Luis Garcia",
                urlImagenUser: "http://gex.mediotiempo.media/32323.jpg" , 
                timestamp: "2014-03-12T15:43:59Z",
                titulo: "Vamos a ganar"
                comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non nunc gravida, porta urna nec, volutpat quam. Nullam consequat lacus ante, et auctor justo congue ut. Integer viverra viverra massa id malesuada",
                foto: {
                    idFoto: 32323
                    urlImagen: "http://gex.mediotiempo.media/32323.jpg" ,
                    likes: 54,
                    comentariosCantidad: 
                }
            }
        ]


### Agregar comentarios a un partido [POST]
Servicio que agrega un comentario para un partido dado. Valores esperados: `idMatch` , `comment` , `idPhoto` (opcional). Nota: para subir una foto con el comentario debe incluirse `idPhoto` . `idPhoto` es producto del servicio  <i>ALTA_FOTO</i>.

+ Request (application/json)

    + Headers
    
            X-Auth-Token: {token}

    + Body

            {"idMatch":"50143" , "comment":"678" , "idPhoto":"335684" }
            


+ Response 200 (application/json)


        {
            code : 200 ,
            message: Comentario agregado"
        }



## Comentarios de Foto [/picture_comments]

### Listado de comentarios de una foto [GET]
El servicio regresa un listado de comentarios para una foto. Valores esperados: `idPhoto` , `start` (id del ultimo comentario) , `count` (cantidad de cometarios a traer).  Nota: este servicio no devuelve fotos

+ Request (application/json)

    + Headers
    
            X-Auth-Token: {token}

    + Body

            {"idPhoto":"7895" }
            


+ Response 200 (application/json)


        {
            idComentario: 430 ,
            idUser: 9189,
            nombreUser: "Noel Castillo",
            urlImagenUser: "http://gex.mediotiempo.media/32323.jpg" , 
            timestamp: "2014-03-12T15:43:59Z",
            titulo: "Vamos a ganar"
            comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non nunc gravida, porta urna nec, volutpat quam. Nullam consequat lacus ante, et auctor justo congue ut. Integer viverra viverra massa id malesuada",
        },
        {
            idComentario: 431 ,
            idUser: 9189,
            nombreUser: "Noel Castillo",
            urlImagenUser: "http://gex.mediotiempo.media/32323.jpg" , 
            timestamp: "2014-03-12T15:43:59Z",
            titulo: "Vamos a ganar"
            comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non nunc gravida, porta urna nec, volutpat quam. Nullam consequat lacus ante, et auctor justo congue ut. Integer viverra viverra massa id malesuada",
        },
        {
            idComentario: 432 ,
            idUser: 9189,
            nombreUser: "Noel Castillo",
            urlImagenUser: "http://gex.mediotiempo.media/32323.jpg" , 
            timestamp: "2014-03-12T15:43:59Z",
            titulo: "Vamos a ganar"
            comentario: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non nunc gravida, porta urna nec, volutpat quam. Nullam consequat lacus ante, et auctor justo congue ut. Integer viverra viverra massa id malesuada",
        }


## Torneos [/tournaments]

### Listado de torneos [GET]
El servicio regresa el listado de torneos. Valores esperados: `idFoto` , `start` (id del ultimo comentario) , `count` (cantidad de cometarios a traer).  Nota: este servicio no devuelve fotos

+ Request (application/json)

    + Headers
    
            X-Auth-Token: {token}

    + Body

            {}

+ Response 200 (application/json)


        [
            {
                idTorneo: 447,
                nombre: "Primera División Mexicana",
                abreviacion: "C2014",
                faseActual: 1,
                fechaActual: 10,
                fase: 
                    [ 
                        {
                            idFase: 1,
                            nombre: "Jornada",
                            abreviacion: "J",
                            totalFechas: 15
                        }
                    ]
            },
            {
                idTorneo: 424,
                nombre: "Liga de Campeones CONCACAF",
                abreviacion: "Liga de Campeones CONCACAF",
                faseActual: 3,
                fechaActual: 1,
                fase: 
                    [ 
                        {
                            idFase: 17,
                            nombre: "Fase Grupos",
                            abreviacion: "G",
                            totalFechas: 1
                        },
                        {
                            idFase: 3,
                            nombre: "Cuartos",
                            abreviacion: "C",
                            totalFechas: 2
                        }
                    ]
            },
            {
                idTorneo: 424,
                nombre: "Copa de Oro",
                abreviacion: "CO2013",
                faseActual: 5,
                fechaActual: 1,
                fase: 
                    [ 
                        {
                            idFase: 1,
                            nombre: "Jornada",
                            abreviacion: "J",
                            totalFechas: 3
                        },
                        {
                            idFase: 3,
                            nombre: "Cuartos",
                            abreviacion: "C",
                            totalFechas: 1
                        },
                        {
                            idFase: 4,
                            nombre: "Semifinal",
                            abreviacion: "S",
                            totalFechas: 1
                        },
                        {
                            idFase: 5,
                            nombre: "Final",
                            abreviacion: "F",
                            totalFechas: 1
                        }
                    ]
            }
        ]


## Jornadas [/v1/tournaments/{tournamentId}/phases/{phaseId}/rounds/{week}/matches]
Fuente: http://feeds.mediotiempo.com/sindicacion/partidos/activos.xml

### Listado de partidos por jornada [GET]
El servicio regresa el listado de partidos por Jornada . Valores esperados: `idTournament` , `idPhase` y `numPhase` .

+ Headers
    
        X-Auth-Token: {token}

+ Response 200 (application/json)

        {
            "poweredBy": "mediotiempo.com | La casa del futbol", 
            "tournament": {
                "fase": 1, 
                "id": 447, 
                "jornada": {
                    "fecha": [
                        {
                            "dia": "Viernes 07 de Febrero, 2014", 
                            "partido": {
                                "estatus": 2, 
                                "fecha": "2014-02-07", 
                                "grupo": 1, 
                                "hora": "21:30", 
                                "id": 51332, 
                                "local": {
                                    "content": "Club Tijuana", 
                                    "id": 341
                                }, 
                                "marcador": "2-1", 
                                "relacionados": {
                                    "relacionado": [
                                        {
                                            "content": "futbol/mexico/galerias/2014/02/xolos-muerde-en-casa-a-rayados", 
                                            "id": 11833, 
                                            "tipo": "galeria"
                                        }, 
                                        {
                                            "content": "futbol/mexico/noticias/2014/02/05/visita-incomoda-a-la-frontera", 
                                            "id": 255021, 
                                            "tipo": "previa"
                                        }, 
                                        {
                                            "content": "futbol/mexico/noticias/2014/02/07/tijuana-supero-a-monterrey-y-sigue-invicto-en-casa", 
                                            "id": 255257, 
                                            "tipo": "cronica"
                                        }, 
                                        {
                                            "content": 27, 
                                            "tipo": "ficha"
                                        }, 
                                        {
                                            "content": 64, 
                                            "tipo": "bitacora"
                                        }
                                    ]
                                }, 
                                "visitante": {
                                    "content": "Monterrey", 
                                    "id": 41
                                }
                            }
                        }, 
                        {
                            "dia": "Sábado 08 de Febrero, 2014", 
                            "partido": [
                                {
                                    "estatus": 2, 
                                    "fecha": "2014-02-08", 
                                    "grupo": 1, 
                                    "hora": "17:00", 
                                    "id": 51331, 
                                    "local": {
                                        "content": "América", 
                                        "id": 20
                                    }, 
                                    "marcador": "0-1", 
                                    "relacionados": {
                                        "relacionado": [
                                            {
                                                "content": "futbol/mexico/galerias/2014/02/aguilas-pierden-invicto-en-casa", 
                                                "id": 11837, 
                                                "tipo": "galeria"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/06/aguilas-buscaran-confirmar-ante-tambaleantes-tuzos", 
                                                "id": 255071, 
                                                "tipo": "previa"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/08/debutante-tuzo-chamaqueo-al-america-en-el-azteca", 
                                                "id": 255323, 
                                                "tipo": "cronica"
                                            }, 
                                            {
                                                "content": 28, 
                                                "tipo": "ficha"
                                            }, 
                                            {
                                                "content": 90, 
                                                "tipo": "bitacora"
                                            }
                                        ]
                                    }, 
                                    "visitante": {
                                        "content": "Pachuca", 
                                        "id": 36
                                    }
                                }, 
                                {
                                    "estatus": 2, 
                                    "fecha": "2014-02-08", 
                                    "grupo": 1, 
                                    "hora": "19:00", 
                                    "id": 51335, 
                                    "local": {
                                        "content": "Tigres", 
                                        "id": 45
                                    }, 
                                    "marcador": "1-1", 
                                    "relacionados": {
                                        "relacionado": [
                                            {
                                                "content": "futbol/mexico/galerias/2014/02/volcan-inactivo", 
                                                "id": 11839, 
                                                "tipo": "galeria"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/06/tigres-busca-revivir-en-la-liga-ante-santos", 
                                                "id": 255061, 
                                                "tipo": "previa"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/08/tigres-se-hunde-en-maldicion-santista", 
                                                "id": 255341, 
                                                "tipo": "cronica"
                                            }, 
                                            {
                                                "content": 27, 
                                                "tipo": "ficha"
                                            }, 
                                            {
                                                "content": 120, 
                                                "tipo": "bitacora"
                                            }
                                        ]
                                    }, 
                                    "visitante": {
                                        "content": "Santos", 
                                        "id": 37
                                    }
                                }, 
                                {
                                    "estatus": 2, 
                                    "fecha": "2014-02-08", 
                                    "grupo": 1, 
                                    "hora": "20:00", 
                                    "id": 51329, 
                                    "local": {
                                        "content": "León", 
                                        "id": 164
                                    }, 
                                    "marcador": "1-2", 
                                    "relacionados": {
                                        "relacionado": [
                                            {
                                                "content": "futbol/mexico/galerias/2014/02/pumas-no-respeta-ni-al-campeon", 
                                                "id": 11841, 
                                                "tipo": "galeria"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/07/leon-buscara-volver-a-la-victoria-pumas-a-confirmarse-en-la-liga", 
                                                "id": 255213, 
                                                "tipo": "previa"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/08/pumas-confirmo-tercer-rugido-ante-el-campeon", 
                                                "id": 255351, 
                                                "tipo": "cronica"
                                            }, 
                                            {
                                                "content": 28, 
                                                "tipo": "ficha"
                                            }, 
                                            {
                                                "content": 80, 
                                                "tipo": "bitacora"
                                            }
                                        ]
                                    }, 
                                    "visitante": {
                                        "content": "Pumas", 
                                        "id": 40
                                    }
                                }, 
                                {
                                    "estatus": 2, 
                                    "fecha": "2014-02-08", 
                                    "grupo": 1, 
                                    "hora": "21:00", 
                                    "id": 51336, 
                                    "local": {
                                        "content": "Atlas", 
                                        "id": 22
                                    }, 
                                    "marcador": "1-1", 
                                    "relacionados": {
                                        "relacionado": [
                                            {
                                                "content": "futbol/mexico/galerias/2014/02/los-hermanos-no-se-hicieron-dano", 
                                                "id": 11843, 
                                                "tipo": "galeria"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/07/atlas-recibe-a-morelia-en-duelo-de-hermanos", 
                                                "id": 255165, 
                                                "tipo": "previa"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/08/el-duelo-de-hermanos-termino-1-1", 
                                                "id": 255353, 
                                                "tipo": "cronica"
                                            }, 
                                            {
                                                "content": 27, 
                                                "tipo": "ficha"
                                            }, 
                                            {
                                                "content": 66, 
                                                "tipo": "bitacora"
                                            }
                                        ]
                                    }, 
                                    "visitante": {
                                        "content": "Morelia", 
                                        "id": 31
                                    }
                                }
                            ]
                        }, 
                        {
                            "dia": "Domingo 09 de Febrero, 2014", 
                            "partido": [
                                {
                                    "estatus": 2, 
                                    "fecha": "2014-02-09", 
                                    "grupo": 1, 
                                    "hora": "12:00", 
                                    "id": 51328, 
                                    "local": {
                                        "content": "Puebla", 
                                        "id": 168
                                    }, 
                                    "marcador": "0-1", 
                                    "relacionados": {
                                        "relacionado": [
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/06/chivas-a-ganar-fuera-un-ano-despues", 
                                                "id": 255147, 
                                                "tipo": "previa"
                                            }, 
                                            {
                                                "content": "futbol/mexico/galerias/2014/02/el-rebano-volvio-a-ganar-fuera-de-casa", 
                                                "id": 11847, 
                                                "tipo": "galeria"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/09/el-rebano-celebro-feliz-un-triste-aniversario", 
                                                "id": 255401, 
                                                "tipo": "cronica"
                                            }, 
                                            {
                                                "content": 28, 
                                                "tipo": "ficha"
                                            }, 
                                            {
                                                "content": 83, 
                                                "tipo": "bitacora"
                                            }
                                        ]
                                    }, 
                                    "visitante": {
                                        "content": "Chivas", 
                                        "id": 47
                                    }
                                }, 
                                {
                                    "estatus": 2, 
                                    "fecha": "2014-02-09", 
                                    "grupo": 1, 
                                    "hora": "12:00", 
                                    "id": 51330, 
                                    "local": {
                                        "content": "Toluca", 
                                        "id": 34
                                    }, 
                                    "marcador": "2-0", 
                                    "relacionados": {
                                        "relacionado": [
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/09/isaac-brizuela-es-un-crack-cardozo", 
                                                "id": 255411, 
                                                "tipo": "previa"
                                            }, 
                                            {
                                                "content": "futbol/mexico/galerias/2014/02/los-diablos-derrotaron-a-chiapas", 
                                                "id": 11849, 
                                                "tipo": "galeria"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/07/diablos-y-jaguares-con-rachas-encontradas", 
                                                "id": 255245, 
                                                "tipo": "previa"
                                            }, 
                                            {
                                                "content": 28, 
                                                "tipo": "ficha"
                                            }, 
                                            {
                                                "content": 99, 
                                                "tipo": "bitacora"
                                            }
                                        ]
                                    }, 
                                    "visitante": {
                                        "content": "Chiapas FC", 
                                        "id": 33
                                    }
                                }, 
                                {
                                    "estatus": 2, 
                                    "fecha": "2014-02-09", 
                                    "grupo": 1, 
                                    "hora": "17:00", 
                                    "id": 51333, 
                                    "local": {
                                        "content": "Atlante", 
                                        "id": 15
                                    }, 
                                    "marcador": "1-4", 
                                    "relacionados": {
                                        "relacionado": [
                                            {
                                                "content": "futbol/mexico/galerias/2014/02/soberbio-y-sin-piedad-cruz-azul-hunde-al-potro", 
                                                "id": 11851, 
                                                "tipo": "galeria"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/07/buscaran-potros-puntos-ante-el-lider-cruz-azul", 
                                                "id": 255255, 
                                                "tipo": "previa"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/09/cruz-azul-arrollo-a-los-potros-en-cancun", 
                                                "id": 255451, 
                                                "tipo": "cronica"
                                            }, 
                                            {
                                                "content": 28, 
                                                "tipo": "ficha"
                                            }, 
                                            {
                                                "content": 74, 
                                                "tipo": "bitacora"
                                            }
                                        ]
                                    }, 
                                    "visitante": {
                                        "content": "Cruz Azul", 
                                        "id": 1
                                    }
                                }, 
                                {
                                    "estatus": 2, 
                                    "fecha": "2014-02-09", 
                                    "grupo": 1, 
                                    "hora": "17:00", 
                                    "id": 51334, 
                                    "local": {
                                        "content": "Club Querétaro", 
                                        "id": 43
                                    }, 
                                    "marcador": "2-0", 
                                    "relacionados": {
                                        "relacionado": [
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/07/gallos-y-tiburones-a-recuperar-el-paso", 
                                                "id": 255209, 
                                                "tipo": "previa"
                                            }, 
                                            {
                                                "content": "futbol/mexico/galerias/2014/02/queretaro-tuvo-heroico-triunfo-ante-veracruz", 
                                                "id": 11853, 
                                                "tipo": "galeria"
                                            }, 
                                            {
                                                "content": "futbol/mexico/noticias/2014/02/09/con-dos-menos-queretaro-hunde-al-tiburon", 
                                                "id": 255453, 
                                                "tipo": "cronica"
                                            }, 
                                            {
                                                "content": 28, 
                                                "tipo": "ficha"
                                            }, 
                                            {
                                                "content": 65, 
                                                "tipo": "bitacora"
                                            }
                                        ]
                                    }, 
                                    "visitante": {
                                        "content": "Veracruz", 
                                        "id": 38
                                    }
                                }
                            ]
                        }
                    ], 
                    "id": 6
                }, 
                "name": "Clausura 2014", 
                "start": "2014-01-03"
            }
        }
        


# Group Sprint 5
CheckIns

## Venues [/venues]
### Listado de venues a la redonda [GET]
Este servicio trae los venues a la redonda (distancia max 3km). Valores esperados:  `latitud` y `longitud`.


+ Request (application/json)

    + Headers
    
            X-Auth-Token: {token}

    + Body
    
            {"latitud": "19.3959107", "longitud": "-99.2270293"}


+ Response 200 (application/json)


        {
            idVenue: "4c45b1f274ffc928894277cc" ,
            nombre: "Café Punta del Cielo",
            lat: 19.39606153307067,
            lng: -99.22643423080444
        }


### Alta Venue [PUT]
Este agrega un venue a BD  . Valores esperados: `name` , `description`,`address`, `latitude` y `longitude`. Los valores de descripcion y direccion son opcionales.


+ Request (application/json)

    + Headers
    
            X-Auth-Token: {token}

    + Body
    
            {"name": "nombreVenue","description": "descripcionVenue","address": "direccionVenue","latitude": "19.3959107", "longitude": "-99.2270293"}


+ Response 200 (application/json)


        {
            code : 200 ,
            message: "Venue agregado"
        }

## CheckIn [/checkin]

### Realizar un checkIn [PUT]
Servicio que agrega un checkIn. Hay de dos tipos: 
<br> <b>1.- CheckIn en partido</b> : debe realizar una marcacion sobre el partido (evento) 
<br> <b>2.- CheckIn sobre venue </b>: marcacion sobre un venue (punto) con latitud y longitud. 
<br><br> Valores esperados: `checkInType` (partido o venue), `idVenue` , `idMatch` , `comment` , `idPhoto` , `socialShare` ,  (twitter, facebook) ,`latitude` y `longitude` 
<br><br> <b>Notas :</b> a) Dependiendo el tipo de checkIn sera opcional idMatch(en Venue) o idVenue (por partido). 
b) El campo `comment` debe aceptar un maximo de 140 caracteres. c) El campo `socialShare` acepta valores separados por comas. 
d) Para agregar fotos con el checkIn es necesario apoyarse con el servicio ALTA_FOTO cuyo producto es idPhoto.

+ Request (application/json)

    + Headers
    
            X-Auth-Token: {token}

    + Body
    
            {"checkInType": "partido o venue" , "idVenue": "18635", "idMatch":"12354", "comment": "comentario", "idPhoto": "8993214", "socialShare": "facebook,twitter"  ,"latitude": "19.3959107" , "longitude": "-99.2270293"}


+ Response 200 (application/json)


        {
            code : 200 ,
            message: "CheckIn agregado"
        }